plugins {
    id "com.android.application"
}

android {
    namespace "com.example.dailylist"
    compileSdk 35

    defaultConfig {
        applicationId "com.example.dailylist"
        minSdk 26
        targetSdk 35
        versionCode 9
        versionName "1.6.1"
    }

    sourceSets {
        main {
            manifest.srcFile "../AndroidManifest.xml"
            java.srcDirs = ["../src"]
            res.srcDirs = ["../res"]
        }
    }
}
